-- =====================================================================
-- Hair Korter — curated professional listings
-- Categories: Wigs, Lashes (-> Eyelashes), Locs
-- Areas: North / East / South / West London
--
-- Run AFTER: schema.sql + directory-fields.sql
-- Idempotent: the NOT EXISTS guard skips any Instagram handle already
-- present, so re-running is safe and duplicates are dropped.
--
-- All rows are verified = false (unclaimed) and have no booking_url.
-- Images are placeholders (Unsplash) — swap per professional later.
-- Prices are indicative starting prices; services/bios are minimal.
-- =====================================================================

-- ---------------------------------------------------------------------
-- WIGS  (-> specialty 'Wigs')
-- ---------------------------------------------------------------------
with data(handle, note, reg, price_num) as (
  values
  -- South London
  ('fshairuk','Abbey Wood','South',30),
  ('esteebeautyuk','Lewisham','South',40),
  ('hairbyfavs','Dartford','South',40),
  ('lacedbyprize','Belvedere','South',40),
  ('hdclinique','','South',40),
  ('schair.uk','','South',45),
  ('ilacedit_','Bromley','South',45),
  ('damsstyledit','Camberwell','South',45),
  ('lizdoneitt','Greenwich','South',50),
  ('croydonhairstylist','Croydon','South',50),
  ('cceo.laced','Plumstead','South',55),
  ('thekbstouch','West Croydon','South',55),
  ('theelaceillusion','Camberwell','South',55),
  ('houseeofdynasty','Walworth','South',55),
  ('bycelineatelier','Thornton Heath','South',55),
  ('theehairsurgeonn','Peckham','South',60),
  ('sbparlourr_','Bromley','South',60),
  ('hauseoferiluxe','Charlton','South',60),
  ('floulacediaries','West Croydon','South',60),
  ('slayedbysadee','Croydon','South',65),
  ('zawigs','Greenwich','South',65),
  ('_hdastyless','Catford','South',65),
  ('dbh.loungeuk','Plumstead','South',65),
  ('cshairuk','Thamesmead','South',65),
  ('thelacehouse__','Abbey Wood','South',65),
  ('shlacedit_','South Norwood','South',65),
  ('26suite','Croydon','South',65),
  ('edslaysuk','Sydenham Hill','South',65),
  ('herartistryy','Bermondsey','South',70),
  ('dbxhairuk','Thamesmead','South',70),
  ('msloungeuk','Deptford','South',70),
  ('phirasallure','Tulse Hill','South',70),
  ('_styledbyak_','Elephant & Castle','South',70),
  ('dkhairuk','Croydon','South',70),
  ('_oclounge','Kennington','South',70),
  ('247luxelab','Croydon','South',70),
  ('tlhairuk','Camberwell','South',70),
  ('laidbyjhair','Thornton Heath','South',70),
  ('styledbyauk_','Thamesmead','South',70),
  ('_thebeautysector','Peckham','South',75),
  ('_kadstouch','Walworth','South',75),
  ('kayhairuk','Peckham','South',75),
  ('_hairtherapyy','Walworth','South',75),
  ('hmhairuk','Lewisham','South',75),
  ('aishhairuk','Lewisham','South',75),
  ('byestareuk','Abbey Wood','South',75),
  ('kaysbeautyparlour','Bermondsey','South',75),
  ('marnzmade','Lewisham','South',75),
  ('bkstouch','Erith','South',75),
  ('amzhairuk','Dartford','South',75),
  ('byparishair','Forest Hill','South',80),
  ('tamedbyfaye','Charlton','South',80),
  ('vluxehair','Thamesmead','South',80),
  ('sksuite_','Abbey Wood','South',80),
  ('tbeautelounge','Brixton','South',80),
  ('ricaslays_','Kennington','South',80),
  ('kemiahairuk','Peckham','South',80),
  ('sbeautyuk_','Croydon','South',80),
  ('lacedauk','Kidbrooke','South',80),
  ('sbb.lounge','Croydon','South',80),
  ('rsparlour_','Walworth','South',80),
  ('ajstyles.uk','Elephant & Castle','South',80),
  ('byshardaemarie','Waterloo','South',80),
  ('andrellastouch','Croydon','South',80),
  ('thejenexperience','','South',80),
  ('slayybychanny','Brixton','South',80),
  ('ca.studioss','Orpington','South',80),
  ('cz.beauty','West Norwood','South',80),
  ('dashdeptuk','Old Kent Road','South',80),
  ('hairbyvii_','Bermondsey','South',80),
  ('jaeluxeuk','Old Kent Road','South',80),
  ('beautybythebankz','Thornton Heath','South',85),
  ('nelashairuk','Camberwell','South',85),
  ('theesparlour','Eltham','South',85),
  ('slaywithdmonae','Brixton','South',85),
  ('theokoistudio','','South',85),
  ('etl.lounge','Abbey Wood','South',85),
  ('ceelaidit','Woolwich','South',85),
  ('desiredlace','New Cross Gate','South',85),
  ('thencltouch','Erith','South',85),
  ('kionihairuk','Catford','South',85),
  ('goldhairline_','Dartford','South',85),
  ('slayedbydz','Croydon','South',90),
  ('flo.hairlounge','Lewisham','South',90),
  ('tifahstouch_','Deptford','South',90),
  ('atanouk','Old Kent Road','South',90),
  ('atbstylesuk','Catford','South',90),
  ('thelaceslayer','Lewisham','South',90),
  ('teestoucch','Abbey Wood','South',90),
  ('lacegurulondon','South Croydon','South',90),
  ('chiorahair','Surrey Quays','South',90),
  ('tressendence','Plumstead','South',90),
  ('ts.crowned','Croydon','South',90),
  ('gghairlounge','Croydon','South',90),
  ('hairbyjakelyn','Croydon','South',90),
  ('maisonoceaneltd','Lewisham','South',90),
  ('rayshairhub','Belvedere','South',90),
  ('oyinnstouch','Plumstead','South',90),
  ('themaneover','Mitcham','South',90),
  ('rvthestylist','Old Kent Road','South',90),
  ('lacedbyshy','West Norwood','South',95),
  ('dbdhairstudio','Camberwell','South',95),
  ('laryealdn','Streatham Hill','South',95),
  ('aslayeduk','Woolwich','South',95),
  ('hairrbykayy','Deptford','South',95),
  ('hauseofhairr','Abbey Wood','South',95),
  ('shanxslays','','South',95),
  ('kashstylesuk','Lewisham','South',95),
  ('pelzgalore','Peckham','South',100),
  ('slayedbydams','Peckham','South',100),
  ('cmhairuk','South Wimbledon','South',100),
  ('angeestyles','Old Kent Road','South',100),
  ('nolahairr','Peckham','South',100),
  ('styledbyariii_','Bromley','South',100),
  ('veehairlab','Thornton Heath','South',100),
  ('de.maneuk','Catford','South',100),
  ('dbstyless','Catford','South',105),
  ('isisthehairstylist','Streatham Hill','South',105),
  ('akstylesuk','Deptford','South',110),
  ('knhairlounge','Norbury','South',110),
  ('bynyaasika','Deptford','South',110),
  ('michelleamaldn','Lewisham','South',110),
  ('bslayedit','Old Kent Road','South',110),
  ('jaiistyleditt','Peckham','South',110),
  ('hairbysimmi','Old Kent Road','South',110),
  ('ccs.glamhousehair','Camberwell','South',110),
  ('dynastyluxelounge','Belvedere','South',110),
  ('lba.uk','Bermondsey','South',115),
  ('tressologybydca','Deptford','South',120),
  ('lacedoutuk','Lewisham','South',120),
  ('tamedbyjai','Elephant & Castle','South',125),
  ('bristyl3s','Brixton','South',130),
  ('thelushlabuk','South Wimbledon','South',130),
  ('ggalore_','Bermondsey','South',130),
  ('scalpish.uk','Catford','South',145),
  ('lhairuk','Kennington','South',null),
  ('sleekedpalace','Brixton','South',null),
  ('by.asnathh','Clapham Junction','South',null),
  -- North London
  ('klhairuk','Enfield','North',55),
  ('neyswigs.ldn','','North',55),
  ('adeotistyles','Tottenham','North',65),
  ('hairby_jkay','Tottenham','North',65),
  ('marnshairuk','Edmonton','North',65),
  ('laidbydt','Enfield','North',70),
  ('bbuksthebrand','Enfield','North',70),
  ('theecksuite','Hackney North','North',75),
  ('bmthestylist','Harringey','North',75),
  ('mainbeaute','Tottenham','North',75),
  ('_layere','Enfield, Ponders','North',75),
  ('elluxebeauty','Enfield','North',80),
  ('adelinetresses','Archway','North',80),
  ('rxlaced','Hackney North','North',80),
  ('marahairuk','Stoke Newington','North',80),
  ('josiestouch','Islington','North',85),
  ('lzlaced','Edmonton','North',85),
  ('jpstyledit','Edmonton','North',85),
  ('hairbycc','Tottenham','North',90),
  ('abhairuk','Edmonton','North',90),
  ('prihairuk','','North',95),
  ('cotildascreation','','North',95),
  ('bysephorauk','Waltham Cross','North',100),
  ('miswigs','Wood Green','North',100),
  ('thelacedwayuk','Enfield','North',100),
  ('theetianashantel','Tottenham','North',100),
  ('kumikreates','Islington','North',110),
  ('mkk.lux','Upper Holloway','North',110),
  ('thehairgalore','Enfield','North',110),
  ('edens_hairandbeauty_','Cuffley','North',130),
  ('slayedbybailey','Surrey Quays','North',140),
  ('brwnhair','Tottenham','North',null),
  -- East London
  ('thelaceprintbykells','Shoreditch','East',25),
  ('cbstylesuk','Hackney','East',35),
  ('laidoutuk','Hackney','East',40),
  ('akkollection','Hackney','East',40),
  ('theelaceparlour','Dagenham','East',55),
  ('slaidbyt_','Walthamstow','East',60),
  ('kvdolledit','Ilford','East',55),
  ('jhairuk','Dagenham','East',65),
  ('theeloungeuk','Hackney','East',65),
  ('dvhairuk','Dagenham','East',70),
  ('jjkbeautyldn','Stratford','East',70),
  ('donebydemz_','Romford','East',70),
  ('thejulztouch','Barking','East',70),
  ('mmparlour_','','East',70),
  ('mirastyless_','Canary Wharf','East',75),
  ('slayedbyjessica','Canning Town','East',75),
  ('24lookss','Clapton','East',75),
  ('skbeauty.uk','Canning Town','East',75),
  ('hairbyhml','Dagenham','East',75),
  ('jesslacedituk','Forest Gate','East',75),
  ('theelabniorr','Ilford','East',75),
  ('jistyledit','','East',75),
  ('animasallure','Clapton','East',75),
  ('tktresses','Dagenham','East',80),
  ('keiraslabel','Hackney','East',80),
  ('theelaceroom','Stratford','East',80),
  ('astyleeltd','Clapton','East',85),
  ('thelace_goddess','Clapton','East',85),
  ('sds.uk_','Clapton','East',85),
  ('sleekparlour','Canary Wharf','East',85),
  ('hairbygiulia','Tilbury','East',85),
  ('bhloungee','Canning Town','East',85),
  ('hairbyabie_','Dagenham','East',85),
  ('laceclinique','Ilford','East',85),
  ('debslaidit','Canning Town','East',85),
  ('herstyles.uk','Hackney','East',90),
  ('chihair.uk','Leyton','East',90),
  ('danhislays','Forest Gate','East',90),
  ('nwwiggs','Shoreditch','East',90),
  ('hermshair','Canning Town','East',90),
  ('kutieshairuk','Walthamstow','East',95),
  ('thelacegeek','Romford','East',95),
  ('heautyldn','Dagenham','East',95),
  ('lianedidit','Romford','East',95),
  ('jnbhair_','Hackney Wick','East',95),
  ('stvcksstyles','Docklands','East',100),
  ('elizabethayouk','Custom House','East',100),
  ('rbstyles.uk','Leyton','East',100),
  ('jplaceroom','Forest Gate','East',100),
  ('styledbybritsuk','South Woodford','East',100),
  ('scalpedit','Stratford','East',100),
  ('bynickellecarey','Clapton','East',105),
  ('fhairuk','Bromley by Bow','East',110),
  ('peloamouruk','Clapton','East',110),
  ('thelacecassanova','Custom House','East',110),
  ('vsi.velour','Bromley By Bow','East',115),
  ('mzparlour','Canning Town','East',120),
  ('rgwigs','Leyton','East',120),
  ('precioushair.co','Walthamstow','East',120),
  ('londonhairlounge','Barking','East',120),
  ('theendstylist','Dagenham','East',125),
  ('bylaideldn','Walthamstow','East',130),
  ('rshairuk_','','East',130),
  ('thetiataj','Stratford','East',135),
  ('wigginituk','Gallios Reach','East',135),
  ('bymarieuk','Clapton','East',null),
  -- West London
  ('amberslaays','Hayes','West',70),
  ('rathestylist','North Kensington','West',75),
  ('belloroomuk','Perivale','West',80),
  ('rawmantic_hair','Hayes','West',130),
  ('her.ego','W2','West',null)
),
ins as (
  insert into stylists (
    name, tagline, bio, avatar_url, cover_image_url, region,
    years_experience, price_range, featured, booking_url, instagram_url, verified
  )
  select
    d.handle,
    'Wig installs & styling',
    'Wig installs'
      || case when d.price_num is not null then ' from £' || d.price_num else '' end
      || case when d.note is not null and d.note <> '' and d.note not in ('TBC','area','AREA')
              then ' · ' || d.note else '' end
      || ', ' || d.reg || ' London.',
    'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop',
    'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=800&h=400&fit=crop',
    d.reg::region,
    0,
    (case when d.price_num is null then '££'
          when d.price_num < 50 then '£'
          when d.price_num <= 90 then '££'
          else '£££' end)::price_range,
    false,
    null,
    '@' || d.handle,
    false
  from data d
  where not exists (
    select 1 from stylists s where s.instagram_url = '@' || d.handle
  )
  returning id
)
insert into stylist_specialties (stylist_id, specialty)
select id, 'Wigs'::specialty from ins;


-- ---------------------------------------------------------------------
-- LASHES  (-> specialty 'Eyelashes')  — no prices published
-- ---------------------------------------------------------------------
with data(handle, note, reg) as (
  values
  -- South London
  ('teesbeautylounge','West Norwood','South'),
  ('sbad.uk','Bromley','South'),
  ('renslashlab','Croydon','South'),
  ('lashharbouruk','Stockwell','South'),
  ('shaznewhitebeauty','Streatham','South'),
  ('the.minksbar','Old Kent Road','South'),
  ('teeblinked','Woolwich','South'),
  ('galorebeauti','Bromley','South'),
  ('jaelasheditt_','Bexley','South'),
  ('dlashparlourr','Erith','South'),
  ('dlashaesthetic','New Cross','South'),
  ('hauseofpariss','Croydon','South'),
  ('lashedbytamera','West Norwood','South'),
  ('kkbeautyloungee_','Bromley South','South'),
  ('minkedkartel','South Croydon','South'),
  ('lasheuruk','Deptford','South'),
  ('leoaestheticltd','Peckham','South'),
  ('tsminks.co','South Wimbledon','South'),
  ('bslaysldn','Croydon','South'),
  ('ciasminkss','','South'),
  ('csnlashes_','Clapham','South'),
  ('_perfectminks','Croydon','South'),
  ('minkssbymk','Forest Hill','South'),
  ('thekeylookldn','Plumstead','South'),
  ('indialashedit','South Norwood','South'),
  ('theelashfreak','','South'),
  ('sabeautybaruk','Camberwell','South'),
  ('fslashco','Abbey Wood','South'),
  ('bymarni.lashes','Greenwich','South'),
  ('outlashedbyshy','Croydon','South'),
  ('nae2slae','Camberwell','South'),
  ('lashstoplondon','Lewisham','South'),
  ('klashbarr_','Bexley','South'),
  ('llashedbyts','West Norwood','South'),
  ('eyec.beauty','Croydon','South'),
  ('mariesbeautyuk','New Cross','South'),
  ('thelashfairyldn','Dulwich','South'),
  ('laurentminks','Lower Sydenham','South'),
  ('liyahslashhub','Bromley','South'),
  -- North London
  ('queensparlourr','Tottenham','North'),
  ('ilashdoll','Islington','North'),
  ('linasminkss','Tottenham','North'),
  ('minksgalorex','Archway','North'),
  ('thelashcentral_','Edmonton','North'),
  ('millionsbeautyhub','Tottenham','North'),
  ('ctlashed','Islington','North'),
  ('minkedbyes','Hackney North','North'),
  ('alashuk_','Arnos Grove','North'),
  ('lashroom_uk','Enfield','North'),
  ('jaicosmetiics','Seven Sisters','North'),
  ('techartistryuk','Enfield','North'),
  ('theenhancestudio','Edmonton','North'),
  ('beautyydistrict','Tottenham','North'),
  ('bydeyonna','Enfield','North'),
  ('lashdrops','Finsbury Park','North'),
  -- East London
  ('_lashedbyz','Stratford','East'),
  ('lashesbykayk','Clapton','East'),
  ('mbl_lashes','Stratford','East'),
  ('galorelounge','Clapton','East'),
  ('lai.lashedit','Dagenham','East'),
  ('ddminkedit','','East'),
  ('prettyminksby.t','Canning Town','East'),
  ('kyylashdit','Clapton','East'),
  ('lash.unit','Canning Town','East'),
  ('hashuk_','Leyton','East'),
  ('minkdhub_','Ilford','East'),
  ('nmink.s','Stratford','East'),
  ('laashedby.k','Beckton','East'),
  ('nbeautyukofficial','Hackney','East'),
  ('elsminkss','Custom House','East'),
  ('outlashthem','Rainham','East'),
  ('leaminkedit','Bow','East'),
  ('kingsfactoryy','','East'),
  ('theelondonedit','Clapton','East'),
  ('shansbeautyco','Newham','East'),
  ('chicastudioss','Chingford','East'),
  ('herclinique','Goodmayes','East'),
  ('thelashssurgeon','Ilford','East'),
  ('h.erhaus','Hackney','East'),
  -- West London
  ('lizlasheditt','Chiswick','West'),
  ('melvacalashes','Chiswick','West'),
  ('nelashes__','Northolt','West'),
  ('ayzparlour','Slough','West'),
  ('kraylashhub','Ladbroke Grove','West'),
  ('mslashloungex','Acton','West'),
  ('carmslashline','UB9 & W7','West'),
  ('larnnasfaces','Kew Gardens','West'),
  ('lashlab.bynk','Greenford','West'),
  ('faitoface','Maida Vale','West'),
  ('patricialashess','Ealing','West'),
  ('fantasyflutters','Twickenham','West'),
  ('thelashdolllondon','','West'),
  ('hhcbabe','Northolt','West'),
  ('codysbeautybar','Hayes','West'),
  ('lashandbrowsbyconnie__','Northolt','West')
),
ins as (
  insert into stylists (
    name, tagline, bio, avatar_url, cover_image_url, region,
    years_experience, price_range, featured, booking_url, instagram_url, verified
  )
  select
    d.handle,
    'Lash extensions',
    'Lash extensions'
      || case when d.note is not null and d.note <> '' and d.note not in ('TBC','area','AREA')
              then ' · ' || d.note else '' end
      || ', ' || d.reg || ' London.',
    'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&h=400&fit=crop',
    d.reg::region,
    0,
    '££'::price_range,
    false,
    null,
    '@' || d.handle,
    false
  from data d
  where not exists (
    select 1 from stylists s where s.instagram_url = '@' || d.handle
  )
  returning id
)
insert into stylist_specialties (stylist_id, specialty)
select id, 'Eyelashes'::specialty from ins;


-- ---------------------------------------------------------------------
-- LOCS  (Mens Locticians -> specialty 'Locs')
-- ---------------------------------------------------------------------
with data(handle, note, reg, price_num) as (
  values
  -- South London
  ('styledby.gt','Peckham','South',30),
  ('locdbyrei_','Vauxhall','South',30),
  ('locdbyzahra','Clapham','South',35),
  ('loccedinuk','Deptford','South',35),
  ('indiastouchuk','Bromley','South',40),
  ('nhair_uk','Woolwich','South',40),
  ('theslparlour','Elephant & Castle','South',40),
  ('estlocs','Erith','South',40),
  ('imhairuk','Deptford','South',40),
  ('theagmeffect.uk','Abbey Wood','South',40),
  ('styleddbymae','Clapham Junction','South',45),
  ('fchairuk','Camberwell','South',45),
  ('getloccy','Croydon','South',50),
  ('caribbeandreads','South Norwood','South',50),
  ('hmlocstudio','Camberwell','South',50),
  ('loccedbyams','Surrey Quays','South',50),
  ('zr.parlour','Greenwich','South',50),
  ('merivehair','Woolwich','South',50),
  ('locdbya_','','South',50),
  ('hloungeuk','Belvedere','South',50),
  ('locxedinn','Borough','South',55),
  ('toni.styleshair','Thornton Heath','South',55),
  ('klocs.co','South Norwood','South',55),
  ('mhkstyles','Lewisham','South',55),
  ('ttlocs','Woolwich','South',55),
  ('ivlocsuk','Lewisham','South',55),
  ('thechp.atelier','Lewisham','South',55),
  ('thebraidologistldn','','South',55),
  ('gchairuk_','Croydon','South',60),
  ('l0ccedin_','Greenwich','South',60),
  ('hair.by.nai','Crystal Palace','South',60),
  ('locdbylaura','Catford','South',60),
  ('nsgalore','Thornton Heath','South',60),
  ('brendsstylez','Brixton Hill','South',70),
  ('thelocsden','Elephant & Castle','South',70),
  ('shayy.rv','Wandsworth','South',70),
  ('locxedinldn','Forest Hill','South',70),
  ('bdhairr','Woolwich','South',null),
  ('ebssstyleditt','Abbey Wood','South',null),
  ('cglocs','Woolwich','South',null),
  -- North London
  ('blessedbyela','New Southgate','North',35),
  ('mbstylesuk','Tottenham','North',35),
  ('tlcbytlcuk','Wood Green','North',45),
  ('jcbraideditt','Enfield','North',50),
  ('hairbychans','Tottenham','North',60),
  ('rosabeautylounge','Upper Edmonton','North',60),
  ('locdbyhbv','Palmers Green','North',65),
  ('hairbylaila24','Palmers Green','North',80),
  -- East London
  ('locdbym','Romford','East',30),
  ('aleshalocdit','Essex','East',35),
  ('hair.byjoy','Tilbury','East',35),
  ('jasalocced','Barking','East',35),
  ('melsbeautylounge_','Dagenham','East',40),
  ('nebraidedit','Romford','East',40),
  ('dm.stylez','Romford','East',40),
  ('laidbylin_','','East',45),
  ('klb.styles','Newham','East',50),
  ('laminlocs','Clapton','East',50),
  ('monaeshairstudio','Newham','East',50),
  ('jkm.lockedin','Forest Gate','East',50),
  ('38styles','Hackney Wick','East',50),
  ('shivstylez','Forest Gate','East',55),
  ('touch3dbym','Newham','East',60),
  ('mlondonstudios','Dagenham','East',60),
  ('taecarterstudios','Clapton','East',60),
  ('tressesbyshayy','Canning Town','East',60),
  ('styledbysa_','Forest Gate','East',60),
  ('conceisao_uk','Bow','East',70),
  ('loureluxesalon','Canning Town','East',70),
  ('mluxe.studios','Deptford','East',75),
  ('estellestyledit','','East',75),
  ('aryahairlounge','Clapton','East',80),
  ('eks_effect','Plaistow','East',null),
  -- West London
  ('bekasretwists','Uxbridge','West',40),
  ('ibhairuk','Notting Hill','West',55)
),
ins as (
  insert into stylists (
    name, tagline, bio, avatar_url, cover_image_url, region,
    years_experience, price_range, featured, booking_url, instagram_url, verified
  )
  select
    d.handle,
    'Loc maintenance & styling',
    'Loc maintenance'
      || case when d.price_num is not null then ' from £' || d.price_num else '' end
      || case when d.note is not null and d.note <> '' and d.note not in ('TBC','area','AREA')
              then ' · ' || d.note else '' end
      || ', ' || d.reg || ' London.',
    'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
    'https://images.unsplash.com/photo-1595476108010-b4d1f102b1f1?w=800&h=400&fit=crop',
    d.reg::region,
    0,
    (case when d.price_num is null then '££'
          when d.price_num < 50 then '£'
          when d.price_num <= 90 then '££'
          else '£££' end)::price_range,
    false,
    null,
    '@' || d.handle,
    false
  from data d
  where not exists (
    select 1 from stylists s where s.instagram_url = '@' || d.handle
  )
  returning id
)
insert into stylist_specialties (stylist_id, specialty)
select id, 'Locs'::specialty from ins;
